language: java
jdk:
  - openjdk8
  - openjdk11

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GI6yAHDk/yp07g10UPGZ6R+2CavEugL7HGRJODYYbDna864E9BlCdDdmmc0eR8XFyFK6U0YLM2XyksxrJ6xklUKC7loLQvNb31ZHzUYsX3warlo99ELhJHn9QU5sEwuSz2n7AWXlO0gi+29lENYdal6c5vhlmFABdjcSUZ6OUI4="

addons:
  coverity_scan:
    project:
      name: "jadler-mocking/jadler"
      description: "Build submitted via Travis CI"
    notification_email: jan.dudek.jr@gmail.com
    build_command_prepend: "mvn -T 1C clean"
    build_command:   "mvn -T 1C -DskipTests=true compile"
    branch_pattern: master
